#!/bin/bash

# Install macOS Command Line Tools

set -eu

{

command -v xcode-select >/dev/null || exit

CLT="/Library/Developer/CommandLineTools"

[ "${1-}" != 'force' ] || rm -rf "${CLT}"

install() {
  if ! test -d "${CLT}"; then
    # This temporary file prompts the 'softwareupdate' utility to list the Command Line Tools
    clt_placeholder="/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress"
    sudo touch "${clt_placeholder}"
    echo "Command Line Tools: Installing"
    sudo softwareupdate --install --all
  fi

  # Headless install may have failed, so fallback to original 'xcode-select' method
  if ! test -d "${CLT}" && test -t 0; then
    echo "Installing the Command Line Tools (expect a GUI popup):"
    sudo "/usr/bin/xcode-select" "--install"
    echo "Press any key when the installation has completed."
    save_state="$(/bin/stty -g)"
    /bin/stty raw -echo
    IFS='' read -r -n 1 -d '' "$@"
    /bin/stty "${save_state}"
  fi
  
  if test -d "${CLT}"; then
    sudo "/usr/bin/xcode-select" "--switch" "${CLT}"
    echo "Command Line Tools: Installed"
  else 
    echo "Command Line Tools: Error"
  fi
  
  sudo "/bin/rm" "-f" "${clt_placeholder}"
}

paths() {
  value='/usr/local/sbin'; grep -q "${value}" /etc/paths || sudo sed -i .bak "s|/usr/local/bin|${value}\n&|"  /etc/paths
  value="${CLT}/usr/bin"; grep -q "${value}" /etc/paths || sudo sed -i .bak "s|/usr/local/bin|&\n${value}|" /etc/paths
  sudo rm -f /etc/paths.bak
  value="${CLT}/usr/share/man"; grep -q "${value}" /etc/manpaths || sudo sed -i .bak "s|/usr/local/share/man|&\n${value}|" /etc/manpaths
  sudo rm -f /etc/manpaths.bak
}

install
paths

}
